---

pve:
  hosts: 
    10.0.0.44:

server:
  k3s_token: "some super secret"
  hosts:
    10.0.0.100:
    
agent:
  hosts:
    10.0.0.200:
    10.0.0.201:
    10.0.0.202:

k3s_cluster:
  children:
    server:
    agent:
