---

# - name: Check Memory Usage
#   ansible.builtin.command: free -m
#   register: mem_usage

# - name: Print Memory Usage
#   ansible.builtin.debug:
#     var: mem_usage.stdout_lines

- name: Install Server(s)
  debug:
    msg: "{{ groups['server'].index(inventory_hostname) }}"

- name: Install K3s Server
  ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} INSTALL_K3S_EXEC="server --cluster-init --node-ip {{ inventory_hostname }} --node-external-ip {{ inventory_hostname }} " K3S_TOKEN=m-"{{ groups['server'].index(inventory_hostname) }}" sh -s -
